# Site settings
title: rehtsira.
description: rehtsira.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "rehtsira.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: rehtsira.
user_description: rehtsira.description
user_title: rehtsira.title
email: rehtsira@gmail.com
twitter_username: rehtsira.twitter
github_username:  rehtsira.github
gplus_username:  rehtsira.gplus

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
